export default {
  languages: [
    { label: 'enum.CHINESE', value: 'CHINESE', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.ENGLISH', value: 'ENGLISH', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.FRENCH', value: 'FRENCH', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.PORTUGUESE', value: 'PORTUGUESE', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.SPANISH', value: 'SPANISH', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.RUSSIAN', value: 'RUSSIAN', video: true, thematic: true, interpretation: false, dubbing: true },
    { label: 'enum.GERMAN', value: 'GERMAN', video: true, thematic: true, interpretation: false, dubbing: true },
    { label: 'enum.JAPANESE', value: 'JAPANESE', video: true, thematic: true, interpretation: false, dubbing: true },
    { label: 'enum.KOREAN', value: 'KOREAN', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.ARABIC', value: 'ARABIC', video: true, thematic: true, interpretation: false, dubbing: true },
    { label: 'enum.ITALIAN', value: 'ITALIAN', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.HEBREW', value: 'HEBREW', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.TURKISH', value: 'TURKISH', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.DUTCH', value: 'DUTCH', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.SERBIAN', value: 'SERBIAN', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.ROMANIAN', value: 'ROMANIAN', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.NEWMONGOLIAN', value: 'NEWMONGOLIAN', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.MALAY', value: 'MALAY', video: true, thematic: true, interpretation: false, dubbing: true },
    { label: 'enum.KAMPUCHEA', value: 'KAMPUCHEA', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.THAI', value: 'THAI', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.LAOTIAN', value: 'LAOTIAN', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.URDU', value: 'URDU', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.HINDI', value: 'HINDI', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.VIETNAMESE', value: 'VIETNAMESE', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.SWAHILI', value: 'SWAHILI', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.HAUSA', value: 'HAUSA', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.YORUBA', value: 'YORUBA', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.IGBO', value: 'IGBO', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.LUGANDA', value: 'LUGANDA', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.ZULU', value: 'ZULU', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.LINGALA', value: 'LINGALA', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.FINNISH', value: 'FINNISH', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.NORWEGIAN', value: 'NORWEGIAN', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.SWEDISH', value: 'SWEDISH', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.DANISH', value: 'DANISH', video: true, thematic: true, interpretation: true, dubbing: true },
    { label: 'enum.UYGUR', value: 'UYGUR', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.TIBETAN', value: 'TIBETAN', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.POLISH', value: 'POLISH', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.INDONESIAN', value: 'INDONESIAN', video: true, thematic: true, interpretation: false, dubbing: true },
    { label: 'enum.CZECH', value: 'CZECH', video: true, thematic: true, interpretation: false, dubbing: true },
    { label: 'enum.OTHERLANGUAGE', value: 'OTHERLANGUAGE', video: true, thematic: true, interpretation: true, dubbing: true }
  ],
  areaOfField: [
    { label: 'enum.TELEPLAY', value: 'TELEPLAY', video: true, thematic: false, interpretation: false, dubbing: true },
    { label: 'enum.MOVIE', value: 'MOVIE', video: true, thematic: false, interpretation: false, dubbing: true },
    { label: 'enum.DOCUMENTARY', value: 'DOCUMENTARY', video: true, thematic: false, interpretation: false, dubbing: true },
    { label: 'enum.CARTOON', value: 'CARTOON', video: true, thematic: false, interpretation: false, dubbing: true },
    { label: 'enum.MEDIATECHNOLOGY', value: 'MEDIATECHNOLOGY', video: false, thematic: true, interpretation: true, dubbing: false },
    { label: 'enum.ITTECHNOLOGY', value: 'ITTECHNOLOGY', video: false, thematic: true, interpretation: true, dubbing: false },
    { label: 'enum.ARCHITECTURALENGINEERING', value: 'ARCHITECTURALENGINEERING', video: false, thematic: true, interpretation: true, dubbing: false },
    { label: 'enum.RADIOANDTELEVISION', value: 'RADIOANDTELEVISION', video: false, thematic: true, interpretation: true, dubbing: false },
    { label: 'enum.FOREIGNTRADE', value: 'FOREIGNTRADE', video: false, thematic: true, interpretation: true, dubbing: false },
    { label: 'enum.SPORTSANDENTERTAINMENT', value: 'SPORTSANDENTERTAINMENT', video: false, thematic: true, interpretation: true, dubbing: false },
    { label: 'enum.COPYRIGHTCONTRACT', value: 'COPYRIGHTCONTRACT', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.COMPANYPROFILE', value: 'COMPANYPROFILE', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.PRODUCTDESCRIPTION', value: 'PRODUCTDESCRIPTION', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.STUDYCASE', value: 'STUDYCASE', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.EDUCATION', value: 'EDUCATION', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.LITERATURE', value: 'LITERATURE', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.FINANCE', value: 'FINANCE', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.REDWINE', value: 'REDWINE', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.RESTAURANT', value: 'RESTAURANT', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.COPYWRITER', value: 'COPYWRITER', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.TOURISM', value: 'TOURISM', video: false, thematic: false, interpretation: true, dubbing: false },
    { label: 'enum.AEOLOGICAL', value: 'AEOLOGICAL', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.AVIATION', value: 'AVIATION', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.OTHERFIELD', value: 'OTHERFIELD', video: true, thematic: true, interpretation: true, dubbing: true }
  ],
  applicationScene: [
    { label: 'enum.TVSTATION', value: 'TVSTATION', video: true, thematic: false, interpretation: false, dubbing: true },
    { label: 'enum.NEWMEDIA', value: 'NEWMEDIA', video: true, thematic: false, interpretation: false, dubbing: true },
    { label: 'enum.CINEMA', value: 'CINEMA', video: true, thematic: false, interpretation: false, dubbing: true },
    { label: 'enum.FILMFESTIVAL', value: 'FILMFESTIVAL', video: true, thematic: false, interpretation: false, dubbing: true },
    { label: 'enum.BUSINESSAFFAIRS', value: 'BUSINESSAFFAIRS', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.MEDIA', value: 'MEDIA', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.LOCALIZATION', value: 'LOCALIZATION', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.ONLINERETAILERS', value: 'ONLINERETAILERS', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.PUBLISH', value: 'PUBLISH', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.MARKET', value: 'MARKET', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.PERSONAL', value: 'PERSONAL', video: false, thematic: true, interpretation: false, dubbing: false },
    { label: 'enum.FOREIGNCONTRACT', value: 'FOREIGNCONTRACT', video: false, thematic: false, interpretation: false, dubbing: false },
    { label: 'enum.COMPANYPROFILE', value: 'COMPANYPROFILE', video: false, thematic: false, interpretation: false, dubbing: false },
    { label: 'enum.PRODUCTDESCRIPTION', value: 'PRODUCTDESCRIPTION', video: false, thematic: false, interpretation: false, dubbing: false },
    { label: 'enum.DOCUMENTIMPARTIALITY', value: 'DOCUMENTIMPARTIALITY', video: false, thematic: false, interpretation: false, dubbing: false },
    { label: 'enum.TECHNICALSPECIFICATIONS', value: 'TECHNICALSPECIFICATIONS', video: false, thematic: false, interpretation: false, dubbing: false },
    { label: 'enum.OTHERSCENE', value: 'OTHERSCENE', video: true, thematic: true, interpretation: true, dubbing: true }
  ],
  businessType: [
    { label: 'enum.VIDEOTRANSLATION', value: 'VIDEOTRANSLATION' },
    { label: 'enum.THEMATICTRANSLATION', value: 'THEMATICTRANSLATION' },
    { label: 'enum.INTERPRETATIONSERVICES', value: 'INTERPRETATIONSERVICES' },
    { label: 'enum.DUBBINGSERVICES', value: 'DUBBINGSERVICES' },
    { label: 'enum.INSTANTSERVICES', value: 'INSTANTSERVICES' }
  ],
  orderStatus: [
    { label: 'enum.PENDING', value: 'PENDING' },
    { label: 'enum.OFFERING', value: 'OFFERING' },
    { label: 'enum.PENDINGPAYMENT', value: 'PENDINGPAYMENT' },
    { label: 'enum.ALREADYPAID', value: 'ALREADYPAID' },
    { label: 'enum.PROCESSING', value: 'PROCESSING' },
    { label: 'enum.COMPLETED', value: 'COMPLETED' },
    { label: 'enum.EVALUATED', value: 'EVALUATED' },
    { label: 'enum.NOTACCEPTED', value: 'NOTACCEPTED' },
    { label: 'enum.EXISTPAID', value: 'EXISTPAID' },
    { label: 'enum.CUSTOMERCANCEL', value: 'CUSTOMERCANCEL' },
    { label: 'enum.CUSTOMERDELETE', value: 'CUSTOMERDELETE' }
  ],
  country: [
    { label: '中文', value: 'cn' },
    { label: 'English', value: 'en' }
  ]
}
