<template>
    <div class="fees-table">
        <table cellspacing="0" cellpadding="0" border="0" class="star-table">
            <thead class="fees-header">
                <tr class="fees-header-title">
                    <th colspan="3">
                        {{$t('enum.ENGLISH')}}
                    </th>
                    <th colspan="4">
                        {{$t('fees.table2.string1')}}
                    </th>
                </tr>
                <tr>
                    <th>{{$t('fees.table2.string2')}}</th>
                    <th>{{$t('fees.table2.string3')}}</th>
                    <th>{{$t('fees.table2.string4')}}</th>
                    <th>{{$t('fees.table2.string2')}}</th>
                    <th>{{$t('fees.table2.string5')}}</th>
                    <th>{{$t('fees.table2.string6')}}</th>
                    <th>{{$t('fees.table2.string7')}}</th>
                </tr>
            </thead>
            <tbody class="fees-body">
                <tr>
                    <td rowspan="2">{{$t('fees.table2.string8')}}</td>
                    <td>{{$t('fees.table2.string16')}}</td>
                    <td>120/{{$t('fees.table2.string17')}}</td>
                    <td rowspan="6">{{$t('fees.table2.string9')}}</td>
                    <td>{{$t('enum.FRENCH')}}</td>
                    <td>800</td>
                    <td>900</td>
                </tr>
                <tr>
                    <td>{{$t('fees.table2.string18')}}</td>
                    <td>220/{{$t('fees.table2.string17')}}</td>
                    <td>{{$t('enum.PORTUGUESE')}}</td>
                    <td>800</td>
                    <td>900</td>
                </tr>
                <tr>
                    <td rowspan="2">{{$t('fees.table2.string9')}}</td>
                    <td>{{$t('fees.table2.string16')}}</td>
                    <td>260/{{$t('fees.table2.string17')}}</td>
                    <td>{{$t('enum.SPANISH')}}</td>
                    <td>700</td>
                    <td>800</td>
                </tr>
                <tr>
                    <td>{{$t('fees.table2.string18')}}</td>
                    <td>350/{{$t('fees.table2.string17')}}</td>
                    <td>{{$t('enum.GERMAN')}}</td>
                    <td>700</td>
                    <td>800</td>
                </tr>
                <tr>
                    <td rowspan="2">{{$t('fees.table2.string10')}}</td>
                    <td>{{$t('fees.table2.string16')}}</td>
                    <td>400/{{$t('fees.table2.string17')}}</td>
                    <td>{{$t('enum.RUSSIAN')}}</td>
                    <td>700</td>
                    <td>800</td>
                </tr>
                <tr>
                    <td>{{$t('fees.table2.string18')}}</td>
                    <td>700/{{$t('fees.table2.string17')}}</td>
                    <td>{{$t('fees.table2.string19')}}</td>
                    <td>900</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td rowspan="2" class="no-bottom">{{$t('fees.table2.string11')}}</td>
                    <td>{{$t('fees.table2.string16')}}</td>
                    <td>500/{{$t('fees.table2.string17')}}</td>
                    <td></td>
                    <td>{{$t('enum.OTHERFIELD')}}</td>
                    <td>800</td>
                    <td>900</td>
                </tr>
                <tr>
                    <td>{{$t('fees.table2.string18')}}</td>
                    <td>700/{{$t('fees.table2.string17')}}</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        <table cellspacing="0" cellpadding="0" border="0" class="star-table">
            <thead class="fees-header">
                <tr class="fees-header-title">
                    <th colspan="7">
                        {{$t('fees.table2.string12')}}
                    </th>
                </tr>
                <tr>
                    <th>{{$t('fees.table2.string2')}}</th>
                    <th>{{$t('fees.table2.string5')}}</th>
                    <th>{{$t('fees.table2.string13')}}</th>
                    <th>{{$t('fees.table2.string14')}}</th>
                    <th>{{$t('fees.table2.string2')}}</th>
                    <th>{{$t('fees.table2.string5')}}</th>
                    <th>{{$t('fees.table2.string15')}}</th>
                </tr>
            </thead>
            <tbody class="fees-body">
                <tr>
                    <td rowspan="36" class="no-bottom">{{$t('fees.table2.string9')}}</td>
                    <td>{{$t('enum.FRENCH')}}</td>
                    <td>260</td>
                    <td>380</td>
                    <td rowspan="36" class="no-bottom">{{$t('fees.table2.string10')}}</td>
                    <td>{{$t('enum.FRENCH')}}</td>
                    <td>500</td>
                </tr>
                <tr>
                    <td>{{$t('enum.PORTUGUESE')}}</td>
                    <td>300</td>
                    <td>520</td>
                    <td>{{$t('enum.PORTUGUESE')}}</td>
                    <td>650</td>
                </tr>
                <tr>
                    <td>{{$t('enum.KOREAN')}}</td>
                    <td>240</td>
                    <td>240</td>
                    <td>{{$t('enum.KOREAN')}}</td>
                    <td>500</td>
                </tr>
                <tr>
                    <td>{{$t('enum.RUSSIAN')}}</td>
                    <td>260</td>
                    <td>380</td>
                    <td>{{$t('enum.RUSSIAN')}}</td>
                    <td>500</td>
                </tr>
                <tr>
                    <td>{{$t('enum.SPANISH')}}</td>
                    <td>300</td>
                    <td>520</td>
                    <td>{{$t('enum.SPANISH')}}</td>
                    <td>500</td>
                </tr>
                <tr>
                    <td>{{$t('enum.GERMAN')}}</td>
                    <td>300</td>
                    <td>450</td>
                    <td>{{$t('enum.GERMAN')}}</td>
                    <td>500</td>
                </tr>
                <tr>
                    <td>{{$t('enum.JAPANESE')}}</td>
                    <td>240</td>
                    <td>240</td>
                    <td>{{$t('enum.JAPANESE')}}</td>
                    <td>500</td>
                </tr>
                <tr>
                    <td>{{$t('enum.ARABIC')}}</td>
                    <td>380</td>
                    <td>550</td>
                    <td>{{$t('enum.SWAHILI')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.ITALIAN')}}</td>
                    <td>350</td>
                    <td>520</td>
                    <td>{{$t('enum.HAUSA')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.HEBREW')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.YORUBA')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.TURKISH')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.IGBO')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.DUTCH')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.LUGANDA')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.ROMANIAN')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.LINGALA')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.NEWMONGOLIAN')}}</td>
                    <td>400</td>
                    <td>600</td>
                    <td>{{$t('enum.FINNISH')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.MALAY')}}</td>
                    <td>350</td>
                    <td>520</td>
                    <td>{{$t('enum.NORWEGIAN')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.KAMPUCHEA')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.SWEDISH')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.THAI')}}</td>
                    <td>350</td>
                    <td>520</td>
                    <td>{{$t('enum.ARABIC')}}</td>
                    <td>600</td>
                </tr>
                <tr>
                    <td>{{$t('enum.LAOTIAN')}}</td>
                    <td>400</td>
                    <td>600</td>
                    <td>{{$t('enum.ITALIAN')}}</td>
                    <td>650</td>
                </tr>
                <tr>
                    <td>{{$t('enum.URDU')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.HEBREW')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.HINDI')}}</td>
                    <td>400</td>
                    <td>600</td>
                    <td>{{$t('enum.TURKISH')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.VIETNAMESE')}}</td>
                    <td>350</td>
                    <td>520</td>
                    <td>{{$t('enum.DUTCH')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.SWAHILI')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.SERBIAN')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.HAUSA')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.ROMANIAN')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.YORUBA')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.NEWMONGOLIAN')}}</td>
                    <td>800</td>
                </tr>
                <tr>
                    <td>{{$t('enum.IGBO')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.MALAY')}}</td>
                    <td>650</td>
                </tr>
                <tr>
                    <td>{{$t('enum.LUGANDA')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.KAMPUCHEA')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.ZULU')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.THAI')}}</td>
                    <td>650</td>
                </tr>
                <tr>
                    <td>{{$t('enum.LINGALA')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.LAOTIAN')}}</td>
                    <td>700</td>
                </tr>
                <tr>
                    <td>{{$t('enum.FINNISH')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.URDU')}}</td>
                    <td>1000</td>
                </tr>
                <tr>
                    <td>{{$t('enum.NORWEGIAN')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.HINDI')}}</td>
                    <td>700</td>
                </tr>
                <tr>
                    <td>{{$t('enum.SWEDISH')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.VIETNAMESE')}}</td>
                    <td>650</td>
                </tr>
                <tr>
                    <td>{{$t('enum.UYGUR')}}</td>
                    <td>400</td>
                    <td>600</td>
                    <td>{{$t('enum.UYGUR')}}</td>
                    <td>800</td>
                </tr>
                <tr>
                    <td>{{$t('enum.TIBETAN')}}</td>
                    <td>400</td>
                    <td>600</td>
                    <td>{{$t('enum.TIBETAN')}}</td>
                    <td>800</td>
                </tr>
                <tr>
                    <td>{{$t('enum.POLISH')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td>{{$t('enum.OTHERFIELD')}}</td>
                    <td>1200</td>
                </tr>
                <tr>
                    <td>{{$t('enum.INDONESIAN')}}</td>
                    <td>500</td>
                    <td>800</td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.OTHERLANGUAGE')}}</td>
                    <td>600</td>
                    <td>1000</td>
                    <td></td>
                    <td></td>
                </tr>

            </tbody>
        </table>
    </div>
</template>
<style lang="less">
</style>
