<template>
    <div class="fees-table">
        <table cellspacing="0" cellpadding="0" border="0" class="star-table">
            <thead class="fees-header">
                <tr class="fees-header-title">
                    <th colspan="3">{{$t('fees.table1.string1')}}</th>
                    <th colspan="2">
                        <p>{{$t('fees.table1.string2')}}</p>
                        <p>{{$t('fees.table1.string3')}}</p>
                    </th>
                </tr>
                <tr>
                    <th>{{$t('fees.table1.string4')}}</th>
                    <th>{{$t('fees.table1.string5')}}</th>
                    <th>{{$t('fees.table1.string6')}}</th>
                    <th>{{$t('fees.table1.string7')}}</th>
                    <th>{{$t('fees.table1.string8')}}</th>
                </tr>
            </thead>
            <tbody class="fees-body">
                <tr>
                    <td>{{$t('enum.CHINESE1')}}</td>
                    <td>1800</td>
                    <td>1215</td>
                    <td>260</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.ENGLISH')}}</td>
                    <td>2025</td>
                    <td>1350</td>
                    <td>350</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.FRENCH')}}</td>
                    <td>2500</td>
                    <td>1500</td>
                    <td>400</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.PORTUGUESE1')}}</td>
                    <td>2500</td>
                    <td>1500</td>
                    <td>400</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.SPANISH1')}}</td>
                    <td>2500</td>
                    <td>1500</td>
                    <td>400</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('fees.table1.string13')}}</td>
                    <td>2500</td>
                    <td>1500</td>
                    <td>400</td>
                    <td>{{$t('enum.SWAHILI')}} / {{$t('enum.HAUSA')}} / {{$t('enum.YORUBA')}} / {{$t('enum.IGBO')}} / {{$t('enum.LUGANDA')}} / {{$t('enum.ZULU')}} / {{$t('enum.LINGALA')}}</td>
                </tr>
                <tr>
                    <td>{{$t('enum.ARABIC1')}}</td>
                    <td>2500</td>
                    <td>1500</td>
                    <td>400</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.RUSSIAN')}}</td>
                    <td>2500</td>
                    <td>1500</td>
                    <td>400</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.GERMAN')}}</td>
                    <td>2500</td>
                    <td>1500</td>
                    <td>400</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.JAPANESE')}}</td>
                    <td>1800</td>
                    <td>1350</td>
                    <td>300</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.KOREAN')}}</td>
                    <td>1800</td>
                    <td>1350</td>
                    <td>300</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.INDONESIAN')}}</td>
                    <td>1800</td>
                    <td>1350</td>
                    <td>300</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.MALAY')}}</td>
                    <td>1800</td>
                    <td>1350</td>
                    <td>300</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.NORWEGIAN')}}</td>
                    <td>2500</td>
                    <td>1500</td>
                    <td>400</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.FINNISH')}}</td>
                    <td>2500</td>
                    <td>1500</td>
                    <td>400</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.SWEDISH')}}</td>
                    <td>2500</td>
                    <td>1500</td>
                    <td>400</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.CZECH')}}</td>
                    <td>2500</td>
                    <td>1500</td>
                    <td>400</td>
                    <td></td>
                </tr>
                <tr>
                    <td>{{$t('enum.OTHERLANGUAGE')}}</td>
                    <td>2500</td>
                    <td>1500</td>
                    <td>400</td>
                    <td></td>
                </tr>
                <tr>
                    <td colspan="5" class="fees-desc">
                        <p>{{$t('fees.table1.string9')}}:</p>
                        <p>{{$t('fees.table1.string10')}}</p>
                        <p>{{$t('fees.table1.string11')}}</p>
                        <p>{{$t('fees.table1.string12')}}</p>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</template>
<style lang="less">
</style>
